### PR TITLE
[STUDIO-2561] Fix SECURITY-2844 issue

### PR DESCRIPTION
**Pull request by Minh-Chien**
## Changes
- Use the MasterToSlaveCallable class to limit where the plugin can be executed.

## Relevant issue
- Resolved issue from [SECURITY-2844](https://issues.jenkins.io/browse/SECURITY-2844).

---
## Code Review Checklist
- [x] Make sure you are opening from a topic/feature/bugfix branch (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by duyluonganh** [comment]
@Minh-Chien Have you tested the plugins on Windows, macOS, and Ubuntu yet?

**Comment by Minh-Chien** [comment]
a @duyluonganh, I have tested the plugin on Windows and macOS. I am testing on Ubuntu 20.04.4.

**Comment by Minh-Chien** [comment]
Hi a @duyluonganh , I've finished testing the changes in Katalon Jenkins Plugin on Windows, macOS and Ubuntu. I found no issues.

**Comment by duyluonganh** [comment]
Thanks @Minh-Chien

**Pull request merged**
